# Generated by Django 6.0.5 on 2026-05-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interviews_limit_per_day',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
