# Generated by Django 6.0.5 on 2026-05-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interviews_limit_per_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
