# Generated by Django 6.0.5 on 2026-06-26 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Готово'), ('completed_raw', 'Готово (без AI)')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('contacts', 'Контакты'), ('summary', 'О себе'), ('experience', 'Опыт работы'), ('education', 'Образование'), ('skills', 'Навыки'), ('languages', 'Языки'), ('certifications', 'Курсы и сертификаты')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('raw_content', models.JSONField(default=dict)),
                ('ai_content', models.JSONField(blank=True, null=True)),
                ('user_content', models.JSONField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resumes.resume')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('resume', 'section_type')},
            },
        ),
    ]
