# Generated by Django 6.0.5 on 2026-06-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='resume_photos/'),
        ),
    ]
