# Generated by Django 6.0.5 on 2026-05-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='level',
            field=models.CharField(choices=[('common', 'Без уровня'), ('junior', 'Junior'), ('middle', 'Middle'), ('pro', 'Pro')], default='common', max_length=10),
        ),
    ]
