# Generated by Django 6.0.5 on 2026-05-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewsession_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='strength_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='feedback',
            name='weakness_tags',
            field=models.JSONField(default=list),
        ),
    ]
