# Generated by Django 6.0.5 on 2026-05-27 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_add_tags_to_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_text', models.TextField()),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль вакансии',
                'verbose_name_plural': 'Профили вакансий',
            },
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='vacancy_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='interviews.vacancyprofile'),
        ),
    ]
