# Generated by Django 6.0.5 on 2026-05-27 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_add_vacancy_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('advice', models.JSONField(default=list)),
                ('focus_topics', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advice', to='interviews.interviewsession')),
            ],
            options={
                'verbose_name': 'Совет по сессии',
                'verbose_name_plural': 'Советы по сессиям',
            },
        ),
    ]
