# Generated by Django 6.0.5 on 2026-05-27 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_add_session_advice'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_progress', models.TextField()),
                ('chronic_issues', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('next_steps', models.JSONField(default=list)),
                ('focus_topics', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session_count_at_generation', models.PositiveIntegerField(default=0)),
                ('vacancy_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advice', to='interviews.vacancyprofile')),
            ],
            options={
                'verbose_name': 'Совет по вакансии',
                'verbose_name_plural': 'Советы по вакансиям',
            },
        ),
    ]
