# Generated by Django 6.0.5 on 2026-05-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_add_vacancy_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyadvice',
            name='verdict',
            field=models.TextField(blank=True),
        ),
    ]
