# Generated by Django 6.0.5 on 2026-06-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_add_verdict_to_vacancy_advice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionAdvice',
        ),
    ]
